export const Images = {
    grupoImg: require('../../assets/grupo.png'),
    privImg: require('../../assets/usuario.png'),
    Pasajero: require('../../assets/2.png'),
    Encomienda: require('../../assets/encomienda.jpg'),
    Ciudad: require('../../assets/otros_servicios.png'),
    Perfil: require('../../assets/user.png'),
    Reservas: require('../../assets/reserva.png'),
    Quito: require('../../assets/montana.png'),
    Tena: require('../../assets/selva.png'),
    morning: require('../../assets/salida-del-sol.png'),
    afternoon: require('../../assets/mediodia.png'),
    ninght: require('../../assets/night.png'),
    user: require('../../assets/user.png'),
    otherPerson: require('../../assets/amigo.png'),
    LOGO: require('../../assets/logo.png'),
    Cash: require('../../assets/dinero.png'),
    Market: require('../../assets/market.png'),
    Viajar: require('../../assets/viajar.png'),
    destinatario: require('../../assets/destinatario.png'),
    SinConexion: require('../../assets/SinConexion.png'),
    Turnos: require('../../assets/turnos.png'),
    Logout: require('../../assets/logout.png'),
    Phone: require('../../assets/phone.png'),
};

