export const HANDLEISCONNECTIONACTIVATE = "HANDLEISCONNECTIONACTIVATE";
export const RESETREGISTERFORM = 'RESET_REGISTER_FORM';
export const UPDATEREGISTERFORM = 'UPDATE_REGISTER_FORM';
export const UPDATEREGISTERONE = 'UPDATE_REGISTER_ONE';
export const RESETREGISTERENCOM = 'RESET_REGISTER_ENCOM';
export const UPDATEREGISTERENCOM = 'UPDATE_REGISTER_ENCOM';
export const UPDATEREGISTERONEENCOM = 'UPDATE_REGISTER_ONEENCOM';
export const RESETREGISTERPRIV = 'RESET_REGISTER_PRIV';
export const UPDATEREGISTERPRIV = 'UPDATE_REGISTER_PRIV';
export const UPDATEREGISTERONEPRIV = 'UPDATE_REGISTER_ONEPRIV';
export const SETUSER = 'SER_USER';
export const HANDLEISLOADING = 'HANDLEIS_LOADING';
export const HANDLEISSPLASH = 'HANDLEISSPLASH';
export const HANDLEUSERINFO = 'HANDLEUSERINFO';
export const HANDLEORIGENCITY = "HANDLEORIGENCITY";
export const HANDLEDISTANCE = "HANDLEDISTANCE";
export const HANDLERUTAS = "HANDLERUTAS";
export const HANDLESELECTRUTAS = "HANDLESELECTRUTAS"
export const HANDLECITY = "HANDLECITY"
export const HANDLESERVICE = "HANDLESERVICE";
export const HANDLERESERVATIONLOG = "HANDLERESERVATIONLOG";
export const HANDLEBOLETOUPDATE = "HANDLEBOLETOUPDATE";
export const HANDLECURRENTLOCATION = "HANDLECURRENTLOCATION";
export const HANDLEISINTERNET = "HANDLEISINTERNET"

//TYPES DRIVERS

export const HANDLETYPEACCOUNT = "HANDLETYPEACCOUNT";